### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by kerbingamer376** [lyxell/chromeos-gcc-toolchains#1]
How do I install this, in order to use chromebrew?

**Comment by lyxell** [comment]
@kerbingamer376 Unpack the tarball for your OS provided in the README and put the files in /usr/local. I.e. `cd ~/Downloads && wget https://www.dropbox.com/s/.../*architecture*-cros-linux-gnu-toolchain-160611.tar.gz && tar -xvzf *architecture*-cros-linux-gnu-toolchain-160611.tar.gz && cp -R usr/local/* /usr/local`.

Be careful though, you might have to clean out `/usr/local` if something goes wrong.
